### ISSUE TITLE
problem in extraction  of Gram Panchayat shapefiles

### ISSUE THREAD

**Issue by JimBillyGraham** [justinelliotmeyers/official_india_gram_panchayat_2019_v2011#1]
Dear,
justinelliotmeyers
 I am happy to download the Code which you have uploaded. I have downloaded it But there is a problem in extraction.while extracting the shapefiles for Sate codes 27,28,29 and 33 its not extracting
![Problem in extraction 29](https://user-images.githubusercontent.com/48754930/80956535-0c513380-8e1f-11ea-8b33-0449fea09e10.jpg). I have uploaded the file for India 29 .shp.
kindly give me solution.

**Comment by justinelliotmeyers** [comment]
use winrar to extract

**Comment by JimBillyGraham** [comment]
i am using winrar only

**Comment by JimBillyGraham** [comment]
Dear ,
justinelliotmeyers,
 I am using winrar but its not working. I need your help.

**Comment by justinelliotmeyers** [comment]
Select all .zip files only. then right click and say extract here. i just tried and everything extracts fine. let me know once you try that.

**Comment by JimBillyGraham** [comment]
Dear ,
justinelliotmeyers,
 As you suggested i once again download the winrar  and reinstalled it. And downloaded only the zip file and extracted it. the same problem is coming. I don't know why. Kindly suggest

**Comment by justinelliotmeyers** [comment]
data will be deleted in 24 hours. please let me know when you download it. https://drive.google.com/open?id=1G2LjUz46KWbFSgBOt1-4MSua_S4kp6El

**Comment by JimBillyGraham** [comment]
> data will be deleted in 24 hours. please let me know when you download it. https://drive.google.com/open?id=1G2LjUz46KWbFSgBOt1-4MSua_S4kp6El

Dear justinelliotmeyers,
 Thank you for your help.
It's working.

**Comment by JimBillyGraham** [comment]
Dear Justinelliotmeyers,

Kindly clarify some doubts for me.

1.there are gaps between the polygons.
2.Is there is Towns/cities with respective ward boundary.

kindly clarify it

**Comment by JimBillyGraham** [comment]
Dear justinelliotmeyers,
 Thank you for your help.
It's working.

**Comment by justinelliotmeyers** [comment]
@JimBillyGraham 
1)whatever is here is all that is currently available. You can research and find other sources. If you find them, please notify me.
2)that is expected. 
3)yes, but that is in a different dataset.

**Comment by JimBillyGraham** [comment]
Dear Justin,
what can we do to fill the gaps between  polygons.
Can i get the ward Boundary shapefile with the respective town/city ?
will it be availbale with you?
